default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-builtins
          - flake8-return
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
